### ISSUE TITLE
designing ui/ux for the android version of the website

### ISSUE THREAD

**Issue by subhasmitapradhan** [purnima143/Kurakoo#231]
nowadays most people prefer a smart phone rather than desktop to look for the solutions of their problems. 
Sometime in the future we will oviously need the android version of the app. So better now than future.

keeping the originality of the website creating the android version .
please let me know if I can work on this?

**Comment by codewithvk** [comment]
@purnima143 look it ^

**Comment by subhasmitapradhan** [comment]
sure...I can wait. do let me know when the web app is done.

**Comment by SKV-programmer** [comment]
Hi @subhasmitapradhan I can design the UI and high fidelity wireframes for the mobile app in Figma. Can you assign me this task  ?

**Comment by SKV-programmer** [comment]
Hi @purnima143  I designed the login and sign up pages for Kurakoo app. Kindly provide me the feedback so that I can continue to make other screens.
![Login](https://user-images.githubusercontent.com/59953764/118378437-818a4380-b5f1-11eb-8c16-103b46499f22.jpg)
![Sign Up](https://user-images.githubusercontent.com/59953764/118378439-86e78e00-b5f1-11eb-8fab-687955631cdf.jpg)

**Comment by codewithvk** [comment]
@purnima143 ^

**Comment by purnima143** [comment]
@SKV-programmer Website is not completed yet.I didn't plan to have any android application. So, better if you work on other issue related to web. We will see the android part later.
